# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyWv-A2dGHKca6WPVkcwX2-TJvBMNLFN
"""

from google.colab import files
upload=files.upload()

import pandas as pd
df_vg = pd.read_csv("/content/vgsales.csv.zip")

df_vg['Name'].nunique()
print(df_vg['Name'].nunique())

df_vg['Platform'].value_counts().head(5)
print(df_vg['Platform'].value_counts().head(5))

df_vg['Year'].value_counts().idxmax()
print(df_vg['Year'].value_counts().idxmax())

df_vg.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False)
print(df_vg.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False))

df_vg.groupby('Publisher')['Global_Sales'].mean().sort_values(ascending=False).head(1)
print(df_vg.groupby('Publisher')['Global_Sales'].mean().sort_values(ascending=False).head(1))

df_vg.loc[df_vg['Global_Sales'].idxmax()]
print(df_vg.loc[df_vg['Global_Sales'].idxmax()])

df_vg[df_vg['Year'] > 2010]['Global_Sales'].mean()
print(df_vg[df_vg['Year'] > 2010]['Global_Sales'].mean())

(df_vg['Global_Sales'] > 1.0).sum()
print((df_vg['Global_Sales'] > 1.0).sum())

df_vg.groupby('Genre')['JP_Sales'].sum().sort_values(ascending=False).head(3)
print(df_vg.groupby('Genre')['JP_Sales'].sum().sort_values(ascending=False).head(3))

df_vg[['NA_Sales', 'EU_Sales']].corr()
print(df_vg[['NA_Sales', 'EU_Sales']].corr())

df_vg[df_vg['Global_Sales'] > 5]['Platform'].value_counts().head(1)
print(df_vg[df_vg['Global_Sales'] > 5]['Platform'].value_counts().head(1))

df_vg['NA_Sales'].median()
print(df_vg['NA_Sales'].median())

df_vg.dropna(subset=['Year']).groupby('Year').size()
print(df_vg.dropna(subset=['Year']).groupby('Year').size())

df_vg.groupby('Year')['Global_Sales'].sum().idxmax()
print(df_vg.groupby('Year')['Global_Sales'].sum().idxmax())

df_vg[df_vg['Genre'].isin(['Action', 'Role-Playing'])].groupby('Genre')['Global_Sales'].mean()
print(df_vg[df_vg['Genre'].isin(['Action', 'Role-Playing'])].groupby('Genre')['Global_Sales'].mean())